### ISSUE TITLE
Exception when running integration tests using Eclipse

### ISSUE THREAD

**Issue by slu-it** [testIT-WebTester/webtester-core#30]
When executing webtester-core's integration tests in eclipse the following exception is logged:
```
Exception in thread "Thread-2" org.openqa.selenium.remote.SessionNotFoundException: The FirefoxDriver cannot be used after quit() was called.
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: 'nbookslu2', ip: '172.16.176.63', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_45'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.execute(FirefoxDriver.java:377)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:620)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:670)
	at org.openqa.selenium.remote.RemoteWebDriver.getWindowHandle(RemoteWebDriver.java:537)
	at info.novatec.testit.webtester.eventsystem.events.browser.AbstractBrowserEvent.<init>(AbstractBrowserEvent.java:21)
	at info.novatec.testit.webtester.eventsystem.events.browser.ExceptionEvent.<init>(ExceptionEvent.java:24)
	at info.novatec.testit.webtester.browser.WebDriverBrowser.executeAction(WebDriverBrowser.java:537)
	at info.novatec.testit.webtester.browser.WebDriverBrowser.close(WebDriverBrowser.java:156)
	at info.novatec.testit.webtester.browser.WebDriverBrowserBuilder$1.run(WebDriverBrowserBuilder.java:88)
```
This does not occur in IntelliJ.

**Steps for reproduction:**
- execute the ```integration``` test package as JUnit tests with eclipse
- wait for tests to finish
- look into the console

**Comment by slu-it** [comment]
It looks like a race condition to me.

**Comment by slu-it** [comment]
Issue only affects tests and in a way that's not breaking anything -> Closed
